// Notification templates for TrendSage Market Insights
// Supports Slack, Telegram, and Email notifications

class NotificationTemplates {
  constructor() {
    this.templates = {
      slack: {
        daily_summary: this.createSlackDailySummary,
        alert: this.createSlackAlert,
        error: this.createSlackError
      },
      telegram: {
        daily_summary: this.createTelegramDailySummary,
        alert: this.createTelegramAlert,
        error: this.createTelegramError
      },
      email: {
        daily_summary: this.createEmailDailySummary,
        weekly_report: this.createEmailWeeklyReport
      }
    };
  }

  // Slack Templates
  createSlackDailySummary(data) {
    const sentiment = data.overall_sentiment;
    const sentimentEmoji = sentiment > 0.5 ? '📈' : sentiment < -0.5 ? '📉' : '➡️';
    const sentimentText = sentiment > 0.5 ? 'Positive' : sentiment < -0.5 ? 'Negative' : 'Neutral';

    return {
      text: `📊 Daily Market Insights Report - ${new Date().toLocaleDateString()}`,
      blocks: [
        {
          type: "header",
          text: {
            type: "plain_text",
            text: `📈 Market Insights - ${new Date().toLocaleDateString()}`
          }
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*Overall Market Sentiment:* ${sentimentEmoji} ${sentimentText} (${sentiment.toFixed(2)})\n*Confidence Score:* ${(data.confidence_score * 100).toFixed(1)}%`
          }
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*Key Insights:*\n${data.key_insights.map(insight => `• ${insight}`).join('\n')}`
          }
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*Competitor Highlights:*\n${data.competitor_highlights.map(comp => `• *${comp.name}:* ${comp.sentiment > 0 ? '📈' : '📉'} ${comp.sentiment.toFixed(2)}`).join('\n')}`
          }
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*AI Analysis:*\n${data.ai_analysis}`
          }
        },
        {
          type: "context",
          elements: [
            {
              type: "mrkdwn",
              text: `🤖 Generated by TrendSage AI Pipeline | 📊 ${data.data_points} data points analyzed`
            }
          ]
        }
      ]
    };
  }

  createSlackAlert(alertData) {
    const severity = alertData.severity || 'medium';
    const severityEmoji = {
      'high': '🚨',
      'medium': '⚠️',
      'low': 'ℹ️'
    }[severity];

    return {
      text: `${severityEmoji} Market Alert - ${alertData.title}`,
      blocks: [
        {
          type: "header",
          text: {
            type: "plain_text",
            text: `${severityEmoji} Market Alert`
          }
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*${alertData.title}*\n${alertData.message}`
          }
        },
        {
          type: "section",
          fields: [
            {
              type: "mrkdwn",
              text: `*Competitor:*\n${alertData.competitor}`
            },
            {
              type: "mrkdwn",
              text: `*Severity:*\n${severity.toUpperCase()}`
            },
            {
              type: "mrkdwn",
              text: `*Time:*\n${new Date().toLocaleString()}`
            },
            {
              type: "mrkdwn",
              text: `*Value:*\n${alertData.value}`
            }
          ]
        }
      ]
    };
  }

  createSlackError(errorData) {
    return {
      text: `❌ TrendSage Pipeline Error`,
      blocks: [
        {
          type: "header",
          text: {
            type: "plain_text",
            text: "❌ Pipeline Error Alert"
          }
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*Error:* ${errorData.error}\n*Component:* ${errorData.component}\n*Time:* ${new Date().toLocaleString()}`
          }
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*Details:*\n\`\`\`${errorData.details}\`\`\``
          }
        }
      ]
    };
  }

  // Telegram Templates
  createTelegramDailySummary(data) {
    const sentiment = data.overall_sentiment;
    const sentimentEmoji = sentiment > 0.5 ? '📈' : sentiment < -0.5 ? '📉' : '➡️';
    const sentimentText = sentiment > 0.5 ? 'Positive' : sentiment < -0.5 ? 'Negative' : 'Neutral';

    return {
      text: `📊 *Daily Market Insights Report* - ${new Date().toLocaleDateString()}

${sentimentEmoji} *Overall Market Sentiment:* ${sentimentText} (${sentiment.toFixed(2)})
📊 *Confidence Score:* ${(data.confidence_score * 100).toFixed(1)}%

🔍 *Key Insights:*
${data.key_insights.map(insight => `• ${insight}`).join('\n')}

🏢 *Competitor Highlights:*
${data.competitor_highlights.map(comp => `• *${comp.name}:* ${comp.sentiment > 0 ? '📈' : '📉'} ${comp.sentiment.toFixed(2)}`).join('\n')}

🤖 *AI Analysis:*
${data.ai_analysis}

---
🤖 Generated by TrendSage AI Pipeline | 📊 ${data.data_points} data points analyzed`,
      parse_mode: "Markdown"
    };
  }

  createTelegramAlert(alertData) {
    const severity = alertData.severity || 'medium';
    const severityEmoji = {
      'high': '🚨',
      'medium': '⚠️',
      'low': 'ℹ️'
    }[severity];

    return {
      text: `${severityEmoji} *Market Alert* - ${alertData.title}

*${alertData.title}*
${alertData.message}

*Competitor:* ${alertData.competitor}
*Severity:* ${severity.toUpperCase()}
*Time:* ${new Date().toLocaleString()}
*Value:* ${alertData.value}`,
      parse_mode: "Markdown"
    };
  }

  createTelegramError(errorData) {
    return {
      text: `❌ *TrendSage Pipeline Error*

*Error:* ${errorData.error}
*Component:* ${errorData.component}
*Time:* ${new Date().toLocaleString()}

*Details:*
\`\`\`
${errorData.details}
\`\`\``,
      parse_mode: "Markdown"
    };
  }

  // Email Templates
  createEmailDailySummary(data) {
    return {
      subject: `Daily Market Insights Report - ${new Date().toLocaleDateString()}`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
            .container { max-width: 800px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            .header { text-align: center; border-bottom: 2px solid #1f77b4; padding-bottom: 20px; margin-bottom: 30px; }
            .metric { background-color: #f8f9fa; padding: 15px; margin: 10px 0; border-radius: 5px; border-left: 4px solid #1f77b4; }
            .insight { background-color: #e8f4fd; padding: 15px; margin: 10px 0; border-radius: 5px; }
            .competitor { display: flex; justify-content: space-between; align-items: center; padding: 10px; margin: 5px 0; background-color: #f8f9fa; border-radius: 5px; }
            .sentiment-positive { color: #28a745; }
            .sentiment-negative { color: #dc3545; }
            .sentiment-neutral { color: #6c757d; }
            .footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #dee2e6; color: #6c757d; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>📊 Daily Market Insights Report</h1>
              <p>${new Date().toLocaleDateString()}</p>
            </div>
            
            <div class="metric">
              <h3>📈 Overall Market Sentiment</h3>
              <p><strong>${data.overall_sentiment > 0.5 ? 'Positive' : data.overall_sentiment < -0.5 ? 'Negative' : 'Neutral'}</strong> (${data.overall_sentiment.toFixed(2)})</p>
              <p>Confidence Score: ${(data.confidence_score * 100).toFixed(1)}%</p>
            </div>

            <h3>🔍 Key Insights</h3>
            ${data.key_insights.map(insight => `<div class="insight">• ${insight}</div>`).join('')}

            <h3>🏢 Competitor Performance</h3>
            ${data.competitor_highlights.map(comp => `
              <div class="competitor">
                <span><strong>${comp.name}</strong></span>
                <span class="${comp.sentiment > 0 ? 'sentiment-positive' : comp.sentiment < 0 ? 'sentiment-negative' : 'sentiment-neutral'}">
                  ${comp.sentiment > 0 ? '📈' : '📉'} ${comp.sentiment.toFixed(2)}
                </span>
              </div>
            `).join('')}

            <h3>🤖 AI Analysis</h3>
            <div class="insight">${data.ai_analysis}</div>

            <div class="footer">
              <p>🤖 Generated by TrendSage AI Pipeline | 📊 ${data.data_points} data points analyzed</p>
            </div>
          </div>
        </body>
        </html>
      `,
      text: `
Daily Market Insights Report - ${new Date().toLocaleDateString()}

Overall Market Sentiment: ${data.overall_sentiment > 0.5 ? 'Positive' : data.overall_sentiment < -0.5 ? 'Negative' : 'Neutral'} (${data.overall_sentiment.toFixed(2)})
Confidence Score: ${(data.confidence_score * 100).toFixed(1)}%

Key Insights:
${data.key_insights.map(insight => `• ${insight}`).join('\n')}

Competitor Performance:
${data.competitor_highlights.map(comp => `• ${comp.name}: ${comp.sentiment > 0 ? '📈' : '📉'} ${comp.sentiment.toFixed(2)}`).join('\n')}

AI Analysis:
${data.ai_analysis}

Generated by TrendSage AI Pipeline | ${data.data_points} data points analyzed
      `
    };
  }

  createEmailWeeklyReport(data) {
    return {
      subject: `Weekly Market Analytics Report - Week of ${new Date().toLocaleDateString()}`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
            .container { max-width: 1000px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            .header { text-align: center; border-bottom: 2px solid #1f77b4; padding-bottom: 20px; margin-bottom: 30px; }
            .section { margin: 30px 0; }
            .metric-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 20px 0; }
            .metric-card { background-color: #f8f9fa; padding: 20px; border-radius: 8px; text-align: center; border-left: 4px solid #1f77b4; }
            .chart-placeholder { background-color: #e9ecef; padding: 40px; text-align: center; border-radius: 8px; margin: 20px 0; }
            .footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #dee2e6; color: #6c757d; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>📊 Weekly Market Analytics Report</h1>
              <p>Week of ${new Date().toLocaleDateString()}</p>
            </div>

            <div class="section">
              <h2>📈 Weekly Summary</h2>
              <div class="metric-grid">
                <div class="metric-card">
                  <h3>${data.weekly_metrics.total_data_points}</h3>
                  <p>Total Data Points</p>
                </div>
                <div class="metric-card">
                  <h3>${data.weekly_metrics.avg_sentiment.toFixed(2)}</h3>
                  <p>Average Sentiment</p>
                </div>
                <div class="metric-card">
                  <h3>${data.weekly_metrics.top_performer}</h3>
                  <p>Top Performer</p>
                </div>
                <div class="metric-card">
                  <h3>${data.weekly_metrics.insights_generated}</h3>
                  <p>AI Insights Generated</p>
                </div>
              </div>
            </div>

            <div class="section">
              <h2>📊 Sentiment Trends</h2>
              <div class="chart-placeholder">
                [Sentiment Trend Chart - Connect to your dashboard]
              </div>
            </div>

            <div class="section">
              <h2>🏢 Competitor Analysis</h2>
              ${data.competitor_analysis.map(comp => `
                <div style="background-color: #f8f9fa; padding: 15px; margin: 10px 0; border-radius: 5px;">
                  <h4>${comp.name}</h4>
                  <p>Weekly Sentiment: ${comp.weekly_sentiment.toFixed(2)} | Data Points: ${comp.data_points} | Trend: ${comp.trend}</p>
                </div>
              `).join('')}
            </div>

            <div class="footer">
              <p>🤖 Generated by TrendSage AI Pipeline</p>
            </div>
          </div>
        </body>
        </html>
      `
    };
  }

  // Get template by type and platform
  getTemplate(platform, type, data) {
    if (!this.templates[platform] || !this.templates[platform][type]) {
      throw new Error(`Template not found: ${platform}.${type}`);
    }
    return this.templates[platform][type].call(this, data);
  }
}

module.exports = NotificationTemplates;
